// JSON.parse(document.querySelector('.ud-component--course-landing-page-udlite--curriculum').getAttribute('data-component-props'))

const curriculum = {
  "displayed_sections": [
    {
      "content_length_text": "13:03",
      "content_length": 783,
      "index": 1,
      "items": [
        {
          "can_be_previewed": true,
          "content_summary": "01:57",
          "description": "",
          "id": 22110260,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 30976960,
          "preview_url": "/course/3482168/preview/?startPreviewId=30976960",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22110260",
          "title": "Introduction to Artificial Intelligence in the Workplace",
          "object_index": 1,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": true,
          "content_summary": "03:52",
          "description": "",
          "id": 22357756,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 30996258,
          "preview_url": "/course/3482168/preview/?startPreviewId=30996258",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22357756",
          "title": "What is Artificial Intelligence?",
          "object_index": 2,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": true,
          "content_summary": "04:02",
          "description": "",
          "id": 22358462,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 30997494,
          "preview_url": "/course/3482168/preview/?startPreviewId=30997494",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22358462",
          "title": "What is Learning & Development Function?",
          "object_index": 3,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": true,
          "content_summary": "03:12",
          "description": "",
          "id": 22811835,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31097894,
          "preview_url": "/course/3482168/preview/?startPreviewId=31097894",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22811835",
          "title": "How is AI transforming L&D?",
          "object_index": 4,
          "item_type": "lecture"
        }
      ],
      "lecture_count": 4,
      "title": "Introduction"
    },
    {
      "content_length_text": "19:09",
      "content_length": 1149,
      "index": 2,
      "items": [
        {
          "can_be_previewed": false,
          "content_summary": "04:54",
          "description": "",
          "id": 22358798,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31098302,
          "preview_url": "/course/3482168/preview/?startPreviewId=31098302",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22358798",
          "title": "The Future of Artificial Intelligence & Virtual Reality",
          "object_index": 5,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "03:46",
          "description": "",
          "id": 22813893,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31099442,
          "preview_url": "/course/3482168/preview/?startPreviewId=31099442",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22813893",
          "title": "The Changing Nature of the Workplace",
          "object_index": 6,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "03:56",
          "description": "",
          "id": 22358756,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31100098,
          "preview_url": "/course/3482168/preview/?startPreviewId=31100098",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22358756",
          "title": "How to Prepare The Future Workforce?",
          "object_index": 7,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "02:43",
          "description": "",
          "id": 22813779,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31114830,
          "preview_url": "/course/3482168/preview/?startPreviewId=31114830",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22813779",
          "title": "Introducing AI to your Business?",
          "object_index": 8,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "02:32",
          "description": "",
          "id": 22811843,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31115106,
          "preview_url": "/course/3482168/preview/?startPreviewId=31115106",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22811843",
          "title": "Implement AI Technology for the first time",
          "object_index": 9,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "01:18",
          "description": "",
          "id": 22449906,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31115226,
          "preview_url": "/course/3482168/preview/?startPreviewId=31115226",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22449906",
          "title": "The Pros and Cons of AI",
          "object_index": 10,
          "item_type": "lecture"
        }
      ],
      "lecture_count": 6,
      "title": "Future of AI in the Workplace"
    },
    {
      "content_length_text": "10:40",
      "content_length": 640.75,
      "index": 3,
      "items": [
        {
          "can_be_previewed": false,
          "content_summary": "04:24",
          "description": "",
          "id": 22457728,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31115650,
          "preview_url": "/course/3482168/preview/?startPreviewId=31115650",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22457728",
          "title": "Artificial Intelligence Ethics",
          "object_index": 11,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "01:49",
          "description": "",
          "id": 22457734,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31115758,
          "preview_url": "/course/3482168/preview/?startPreviewId=31115758",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22457734",
          "title": "The Reality of AI & Tips for Success",
          "object_index": 12,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "04:17",
          "description": "",
          "id": 22457736,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31118024,
          "preview_url": "/course/3482168/preview/?startPreviewId=31118024",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22457736",
          "title": "Course Summary",
          "object_index": 13,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "00:10",
          "description": "",
          "id": 22458328,
          "icon_class": "udi udi-file-o",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": null,
          "preview_url": "/new-lecture/22458328/popup/",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22458328",
          "title": "Reflection Activities",
          "object_index": 14,
          "item_type": "lecture"
        }
      ],
      "lecture_count": 4,
      "title": "Course Summary & Reflection Activities"
    }
  ],
  "sections": [
    {
      "content_length_text": "13:03",
      "content_length": 783,
      "index": 1,
      "items": [
        {
          "can_be_previewed": true,
          "content_summary": "01:57",
          "description": "",
          "id": 22110260,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 30976960,
          "preview_url": "/course/3482168/preview/?startPreviewId=30976960",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22110260",
          "title": "Introduction to Artificial Intelligence in the Workplace",
          "object_index": 1,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": true,
          "content_summary": "03:52",
          "description": "",
          "id": 22357756,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 30996258,
          "preview_url": "/course/3482168/preview/?startPreviewId=30996258",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22357756",
          "title": "What is Artificial Intelligence?",
          "object_index": 2,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": true,
          "content_summary": "04:02",
          "description": "",
          "id": 22358462,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 30997494,
          "preview_url": "/course/3482168/preview/?startPreviewId=30997494",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22358462",
          "title": "What is Learning & Development Function?",
          "object_index": 3,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": true,
          "content_summary": "03:12",
          "description": "",
          "id": 22811835,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31097894,
          "preview_url": "/course/3482168/preview/?startPreviewId=31097894",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22811835",
          "title": "How is AI transforming L&D?",
          "object_index": 4,
          "item_type": "lecture"
        }
      ],
      "lecture_count": 4,
      "title": "Introduction"
    },
    {
      "content_length_text": "19:09",
      "content_length": 1149,
      "index": 2,
      "items": [
        {
          "can_be_previewed": false,
          "content_summary": "04:54",
          "description": "",
          "id": 22358798,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31098302,
          "preview_url": "/course/3482168/preview/?startPreviewId=31098302",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22358798",
          "title": "The Future of Artificial Intelligence & Virtual Reality",
          "object_index": 5,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "03:46",
          "description": "",
          "id": 22813893,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31099442,
          "preview_url": "/course/3482168/preview/?startPreviewId=31099442",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22813893",
          "title": "The Changing Nature of the Workplace",
          "object_index": 6,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "03:56",
          "description": "",
          "id": 22358756,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31100098,
          "preview_url": "/course/3482168/preview/?startPreviewId=31100098",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22358756",
          "title": "How to Prepare The Future Workforce?",
          "object_index": 7,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "02:43",
          "description": "",
          "id": 22813779,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31114830,
          "preview_url": "/course/3482168/preview/?startPreviewId=31114830",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22813779",
          "title": "Introducing AI to your Business?",
          "object_index": 8,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "02:32",
          "description": "",
          "id": 22811843,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31115106,
          "preview_url": "/course/3482168/preview/?startPreviewId=31115106",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22811843",
          "title": "Implement AI Technology for the first time",
          "object_index": 9,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "01:18",
          "description": "",
          "id": 22449906,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31115226,
          "preview_url": "/course/3482168/preview/?startPreviewId=31115226",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22449906",
          "title": "The Pros and Cons of AI",
          "object_index": 10,
          "item_type": "lecture"
        }
      ],
      "lecture_count": 6,
      "title": "Future of AI in the Workplace"
    },
    {
      "content_length_text": "10:40",
      "content_length": 640.75,
      "index": 3,
      "items": [
        {
          "can_be_previewed": false,
          "content_summary": "04:24",
          "description": "",
          "id": 22457728,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31115650,
          "preview_url": "/course/3482168/preview/?startPreviewId=31115650",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22457728",
          "title": "Artificial Intelligence Ethics",
          "object_index": 11,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "01:49",
          "description": "",
          "id": 22457734,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31115758,
          "preview_url": "/course/3482168/preview/?startPreviewId=31115758",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22457734",
          "title": "The Reality of AI & Tips for Success",
          "object_index": 12,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "04:17",
          "description": "",
          "id": 22457736,
          "icon_class": "udi udi-play-circle",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": 31118024,
          "preview_url": "/course/3482168/preview/?startPreviewId=31118024",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22457736",
          "title": "Course Summary",
          "object_index": 13,
          "item_type": "lecture"
        },
        {
          "can_be_previewed": false,
          "content_summary": "00:10",
          "description": "",
          "id": 22458328,
          "icon_class": "udi udi-file-o",
          "is_coding_exercise": false,
          "has_linked_workspace": false,
          "landing_page_url": null,
          "video_asset_id": null,
          "preview_url": "/new-lecture/22458328/popup/",
          "learn_url": "/course/introduction-to-artificial-intelligence-in-the-workplace/learn/lecture/22458328",
          "title": "Reflection Activities",
          "object_index": 14,
          "item_type": "lecture"
        }
      ],
      "lecture_count": 4,
      "title": "Course Summary & Reflection Activities"
    }
  ],
  "num_undisplayed_sections": 0,
  "estimated_content_length_text": "42:53",
  "estimated_content_length_in_seconds": 2573,
  "is_for_practice_test_course": false,
  "num_of_published_lectures": 14,
  "is_limited_consumption_trial": false,
  "url": "/course/introduction-to-artificial-intelligence-in-the-workplace/",
  "tracking_id": "dcaK9bNFSauGq_K5UTzaww"
}